version: '3'

services:
  nodejs-env-dev-in-docker:
    image: nodejs-env-dev-in-docker
    build: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3001:3001
      - 5850:5850
      - 9229:9229
    command: npm run container:dev

  # app2slow:
  #   image: nodejs-env-dev-in-docker-app2slow
  #   build: .
  #   # volumes:
  #   #   - .:/usr/src/app
  #   #   - app2slow_node_modules:/usr/src/app/node_modules
  #   ports:
  #     - 3002:3002
  #   command: node index2.js

volumes:
  node_modules:
  # app2slow_node_modules:
