name: ci-test-version

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  test-version:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ACTION }}

    - name: Test Version
      run: |
        npm t

    - name: Get version number
      run: |
        export APP_VERSION=$(node app-version.js)
        echo $APP_VERSION
