name: ci-test-version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-version:

    if: |
      contains(github.event.pull_request.title, '/bump/major/')
      ||
      contains(github.event.pull_request.title, '/bump/minor/')
      ||
      contains(github.event.pull_request.title, '/bump/patch/')

    runs-on: ubuntu-latest

    steps:

    - name: Test Version
      run: |
        npm t

    - name: Get version number
      run: |
        export APP_VERSION=$(node app-version.js)
        echo $APP_VERSION
