name: ci-test-version

on:
  pull_request:
    branches: [ master, develop ]

jobs:

  test-version:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    #   with:
    #     token: ${{ secrets.TOKEN_ACTION }}

    - name: Setup GIT
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"


    - name: Test Version
      run: |
        npm t

    - name: Get version number
      run: |
        export APP_VERSION=$(node app-version.js)
        echo $APP_VERSION
